<a href="https://colab.research.google.com/github/Dhruv-kys/TORCH-NOTEBOOK/blob/main/model_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Dataset

In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [17]:
df.shape

(569, 33)

In [19]:
df.drop(columns=['id','Unnamed: 32'], inplace = True)

### train test split

In [20]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [21]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [22]:
x_train

array([[-5.80452782e-01, -3.62156721e-01, -5.75885735e-01, ...,
        -7.80107277e-01,  3.01405696e-01, -7.05115700e-01],
       [-6.37300388e-01, -1.07019420e+00, -5.74234694e-01, ...,
        -8.14691799e-01, -2.33070388e-01,  1.15640846e+00],
       [-1.51253362e-01,  1.31222506e+00, -1.63951068e-01, ...,
         8.04915055e-02, -3.59220022e-01, -5.25719044e-01],
       ...,
       [-7.76577021e-01, -1.00792380e+00, -7.63278860e-01, ...,
        -7.75475421e-01, -1.75350546e+00, -5.08687716e-01],
       [-1.37041460e-01, -3.69668706e-02, -1.05751882e-01, ...,
         4.24792776e-01, -2.04852706e-01,  2.92920128e-01],
       [-1.12050503e+00, -4.17508185e-01, -1.11329950e+00, ...,
        -1.19620231e+00,  9.70381804e-04, -2.91822138e-01]])

In [23]:
y_train

394    B
145    B
100    M
385    M
246    B
      ..
384    B
137    B
183    B
423    B
217    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [24]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [25]:
y_train

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0])

### Numpy array to PyTorch tensors

In [26]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [27]:
x_train_tensor

tensor([[-5.8045e-01, -3.6216e-01, -5.7589e-01,  ..., -7.8011e-01,
          3.0141e-01, -7.0512e-01],
        [-6.3730e-01, -1.0702e+00, -5.7423e-01,  ..., -8.1469e-01,
         -2.3307e-01,  1.1564e+00],
        [-1.5125e-01,  1.3122e+00, -1.6395e-01,  ...,  8.0492e-02,
         -3.5922e-01, -5.2572e-01],
        ...,
        [-7.7658e-01, -1.0079e+00, -7.6328e-01,  ..., -7.7548e-01,
         -1.7535e+00, -5.0869e-01],
        [-1.3704e-01, -3.6967e-02, -1.0575e-01,  ...,  4.2479e-01,
         -2.0485e-01,  2.9292e-01],
        [-1.1205e+00, -4.1751e-01, -1.1133e+00,  ..., -1.1962e+00,
          9.7038e-04, -2.9182e-01]], dtype=torch.float64)

### Defining the model

In [39]:
class NN():
  def __init__(self,x):
    self.weights = torch.rand(x.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self,x):
    y_pred = torch.sigmoid(torch.matmul(x,self.weights) + self.bias)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilion = 1e-7
    y_pred = torch.clamp(y_pred,epsilion,1-epsilion)
    loss = -torch.mean(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))
    return loss

In [42]:
learning_rate = 0.1
epochs = 50

### Training pipeline

In [43]:
model = NN(x_train_tensor)

# Define loop
for epoch in range(epochs):

  # Forward pass
  y_pred = model.forward(x_train_tensor)
  # loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  # backward pass
  loss.backward()
  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  #zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.4932342421600726
Epoch: 2, Loss: 3.3691117733697586
Epoch: 3, Loss: 3.2325336109809824
Epoch: 4, Loss: 3.092528810405357
Epoch: 5, Loss: 2.9518366062933734
Epoch: 6, Loss: 2.8078267365085976
Epoch: 7, Loss: 2.6570239197704097
Epoch: 8, Loss: 2.5073753327388912
Epoch: 9, Loss: 2.3554884315711266
Epoch: 10, Loss: 2.202260489188547
Epoch: 11, Loss: 2.0477784439597726
Epoch: 12, Loss: 1.8979482991222631
Epoch: 13, Loss: 1.7552538973335086
Epoch: 14, Loss: 1.6171807507733444
Epoch: 15, Loss: 1.4869021062539043
Epoch: 16, Loss: 1.3629041418478154
Epoch: 17, Loss: 1.252446919637419
Epoch: 18, Loss: 1.1564860091994116
Epoch: 19, Loss: 1.075440223590075
Epoch: 20, Loss: 1.009013812770142
Epoch: 21, Loss: 0.9561211664069152
Epoch: 22, Loss: 0.9149776314834546
Epoch: 23, Loss: 0.8833802571615605
Epoch: 24, Loss: 0.8590870379267377
Epoch: 25, Loss: 0.8401283628989685
Epoch: 26, Loss: 0.8249552218647035
Epoch: 27, Loss: 0.8124439431335627
Epoch: 28, Loss: 0.8018240325074916
Epoch: 29, Loss: 0.7925850666143421
Epoch: 30, Loss: 0.7843935082770318
Epoch: 31, Loss: 0.7770301126823649
Epoch: 32, Loss: 0.7703473463822997
Epoch: 33, Loss: 0.7642421594199564
Epoch: 34, Loss: 0.758639206965894
Epoch: 35, Loss: 0.753480713074032
Epoch: 36, Loss: 0.7487203891747615
Epoch: 37, Loss: 0.7443197703516921
Epoch: 38, Loss: 0.7402459761116061
Epoch: 39, Loss: 0.7364703079634105
Epoch: 40, Loss: 0.7329673412167531
Epoch: 41, Loss: 0.7297143126749558
Epoch: 42, Loss: 0.726690689393816
Epoch: 43, Loss: 0.7238778515235335
Epoch: 44, Loss: 0.7212588495630002
Epoch: 45, Loss: 0.7188182119888908
Epoch: 46, Loss: 0.7165417882617863
Epoch: 47, Loss: 0.7144166175355866
Epoch: 48, Loss: 0.7124308166159553
Epoch: 49, Loss: 0.7105734827250876
Epoch: 50, Loss: 0.708834607932459

In [44]:
model.weights

tensor([[ 0.3848],
        [ 0.2333],
        [-0.1861],
        [ 0.1324],
        [-0.2031],
        [ 0.2519],
        [ 0.0686],
        [-0.4150],
        [-0.0039],
        [ 0.5286],
        [ 0.1948],
        [-0.2790],
        [-0.3513],
        [-0.0874],
        [ 0.1581],
        [ 0.1225],
        [ 0.3579],
        [-0.4482],
        [ 0.2546],
        [-0.1102],
        [-0.4408],
        [ 0.2415],
        [ 0.3988],
        [ 0.4948],
        [ 0.3052],
        [-0.3729],
        [-0.3631],
        [ 0.0488],
        [-0.0823],
        [-0.1300]], dtype=torch.float64, requires_grad=True)

### Evaluation

In [45]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)

print(y_pred)

tensor([[0.5671],
        [0.2764],
        [0.4215],
        [0.2832],
        [0.3100],
        [0.4991],
        [0.3147],
        [0.4589],
        [0.6625],
        [0.4187],
        [0.3225],
        [0.4258],
        [0.3789],
        [0.3899],
        [0.4247],
        [0.5748],
        [0.5989],
        [0.5546],
        [0.3703],
        [0.5283],
        [0.3061],
        [0.6390],
        [0.4215],
        [0.4818],
        [0.4761],
        [0.3849],
        [0.4616],
        [0.5043],
        [0.3865],
        [0.2456],
        [0.3127],
        [0.3888],
        [0.3896],
        [0.2216],
        [0.3303],
        [0.3037],
        [0.3868],
        [0.5044],
        [0.2461],
        [0.4416],
        [0.2865],
        [0.3580],
        [0.4506],
        [0.5107],
        [0.1898],
        [0.3028],
        [0.2603],
        [0.6264],
        [0.5535],
        [0.5241],
        [0.3422],
        [0.5738],
        [0.4398],
        [0.2225],
        [0.8819],
        [0.6643],
        [0.4201],
        [0.3434],
        [0.4949],
        [0.3329],
        [0.4169],
        [0.4572],
        [0.2573],
        [0.3928],
        [0.6303],
        [0.6362],
        [0.3698],
        [0.4485],
        [0.3902],
        [0.0531],
        [0.5582],
        [0.4173],
        [0.5187],
        [0.3677],
        [0.4739],
        [0.3977],
        [0.1254],
        [0.4386],
        [0.3107],
        [0.3962],
        [0.4093],
        [0.4403],
        [0.2847],
        [0.1891],
        [0.4745],
        [0.4730],
        [0.5346],
        [0.3513],
        [0.5473],
        [0.3119],
        [0.3169],
        [0.3935],
        [0.2747],
        [0.3560],
        [0.5664],
        [0.1439],
        [0.4197],
        [0.5802],
        [0.3759],
        [0.5082],
        [0.2225],
        [0.8803],
        [0.4348],
        [0.4451],
        [0.3550],
        [0.6133],
        [0.4387],
        [0.4187],
        [0.3017],
        [0.2612],
        [0.5696],
        [0.5469],
        [0.3672],
        [0.5149]], dtype=torch.float64)